# SSL for Management GUI
# management.ssl.port       = 15672
# management.ssl.cacertfile = /etc/letsencrypt/live/seedling.mwnl.ce.ncu.edu.tw/chain.pem
# management.ssl.certfile   = /etc/letsencrypt/live/seedling.mwnl.ce.ncu.edu.tw/cert.pem
# management.ssl.keyfile    = /etc/letsencrypt/live/seedling.mwnl.ce.ncu.edu.tw/privkey.pem

# SSL for MQTT (MQTTS)
# ssl_options.cacertfile = /etc/letsencrypt/live/seedling.mwnl.ce.ncu.edu.tw/chain.pem
# ssl_options.certfile   = /etc/letsencrypt/live/seedling.mwnl.ce.ncu.edu.tw/cert.pem
# ssl_options.keyfile    = /etc/letsencrypt/live/seedling.mwnl.ce.ncu.edu.tw/privkey.pem

# Assign ports for MQTT and MQTTS
# mqtt.listeners.ssl.default = 8883
mqtt.listeners.tcp.default = 1883