# SSL for Management GUI
#management.ssl.port       = 15672
#management.ssl.cacertfile = /etc/letsencrypt/live/seedling.mwnl.ce.ncu.edu.tw/chain.pem
#management.ssl.certfile   = /etc/letsencrypt/live/seedling.mwnl.ce.ncu.edu.tw/cert.pem
#management.ssl.keyfile    = /etc/letsencrypt/live/seedling.mwnl.ce.ncu.edu.tw/privkey.pem

# SSL for MQTT (MQTTS)
#ssl_options.cacertfile = /etc/letsencrypt/live/seedling.mwnl.ce.ncu.edu.tw/chain.pem
#ssl_options.certfile   = /etc/letsencrypt/live/seedling.mwnl.ce.ncu.edu.tw/cert.pem
#ssl_options.keyfile    = /etc/letsencrypt/live/seedling.mwnl.ce.ncu.edu.tw/privkey.pem

ssl_options.cacertfile = /etc/rabbitmq/ssl/ca.crt
ssl_options.certfile   = /etc/rabbitmq/ssl/broker.crt
ssl_options.keyfile    = /etc/rabbitmq/ssl/broker.key
ssl_options.verify     = verify_peer
ssl_options.fail_if_no_peer_cert = true

# Assign ports for MQTT and MQTTS
mqtt.listeners.ssl.1 = 8883
mqtt.listeners.ssl.2 = 8884
mqtt.listeners.tcp.default = 1883

